#!/bin/bash
# SCRIPT BY @ASHARIRHMN // Last Update: 08.50 WITA

# Function to kill all aon processes
kill_aon_processes() {
    PIDS=$(ps | grep '[a]on' | grep -v "aon cek" | awk '{print $1}')
    if [[ -n "$PIDS" ]]; then
        echo "Stop AON yang berjalan saat ini..."
        kill -9 $PIDS
        echo "Semua AON sudah berhenti."
    else
        echo "Tidak ada AON ditemukan."
    fi
}

# Function to check aon processes
cek_aon_processes() {
    echo "AON yang sedang berjalan:"
    ps | grep '[a]on' | grep -v "aon cek" | awk '{print $1, $5}' | while read -r pid host; do
        echo "PID: $pid, Host: $host"
    done
}

# Check if a command argument is provided
if [[ -z "$1" ]]; then
    clear
    echo "++++++++++++++++++++++++++++++++++++"
    echo "AON by ASHRWRT @asharirhmn"
    echo "Last update: 30/05/2025 09:35AM"
    echo "++++++++++++++++++++++++++++++++++++"
    echo ""
    echo "
# Jalankan melalui terminal dengan command berikut nohup aon <hostname1> <hostname2> ... > /dev/null 2>&1& . contoh: nohup /usr/bin/aon xl.co.id google.com >/dev/null 2>&1&
# Untuk melihat script berhasil jalan di background atau tidak, pada terminal OpenWRT ketik command aon cek
# TIPS: Agar setiap kali STB OpenWRT restart/reboot menjalankan script ini, tambahkan script ini pada System > Startup (tested on FW Reyre). Ketik command berikut: nohup /usr/bin/aon google.co.id facebook.com >/dev/null 2>&1&
# Kalau kamu suka, kirimkan dukungan/donasi melalui SAWERIA (https://saweria.co/ashr) agar selalu update script terbaru"
    echo ""
    exit 1
fi

SCRIPT_NAME=$(basename "$0")

if [[ "$1" == "kill" ]]; then
    kill_aon_processes
    exit 0
fi

if [[ "$1" == "cek" ]]; then
    clear
    echo "+++++++++++++++++++++++++++"
    echo "AON by ASHRWRT @asharirhmn"
    echo "+++++++++++++++++++++++++++"
    echo ""
    cek_aon_processes
    echo ""
    exit 0
fi

HOSTS=("$@")
echo "Mulai mendapatkan koneksi ke ${HOSTS[*]}..."

# Function to test ping and decide action
ping_host() {
    local HOST=$1
    local FAIL_COUNT=0

    while true; do
        PING_RESULT=$(ping -c 1 $HOST 2>/dev/null)
        if [[ $? -eq 0 ]]; then
            PING_TIME=$(echo "$PING_RESULT" | grep 'time=' | awk -F'time=' '{print $2}' | awk '{print $1}')
            echo "Ping ke $HOST berhasil ($PING_TIME ms)"
            FAIL_COUNT=0 # Reset fail count on success
        else
            FAIL_COUNT=$((FAIL_COUNT + 1))
            echo "Gagal mendapatkan koneksi ke $HOST ($FAIL_COUNT/3)"
            if [[ $FAIL_COUNT -ge 3 ]]; then
                echo "Koneksi ke $HOST gagal tiga kali berturut-turut, auto restart modem lewat /usr/bin/hilink iphunter"
                /usr/bin/hilink iphunter
                service openclash start
                sleep 15
                FAIL_COUNT=0 # Reset fail count after restart
            fi
        fi
        sleep 1
    done
}

for HOST in "${HOSTS[@]}"; do
    ping_host "$HOST" &
done

wait
