#!/bin/bash
# SCRIPT BY @ASHARIRHMN
# version 1.2
# Jalankan melalui terminal dengan command berikut nohup aon <hostname> >/dev/null 2>&1& . contoh: nohup /usr/bin/aon xl.co.id >/dev/null 2>&1&
# Untuk melihat script berhasil jalan di backround atau tidak, pada terminal OpenWRT ketik command pgrep -l aon
# TIPS: Agar setiap kali STB OpenWRT restart/reboot menjalankan script ini, tambahkan script ini pada System > Startup (tested on FW Reyre). Ketik command berikut: nohup /usr/bin/aon google.co.id >/dev/null 2>&1&
# Kalau kamu suka, kirimkan dukungan/donasi melalui SAWERIA (https://saweria.co/ashr) agar selalu update script terbaru

# Function to kill all aon processes
kill_aon_processes() {
    PIDS=$(pgrep -f "$SCRIPT_NAME")
    if [[ -n "$PIDS" ]]; then
        echo "Killing all aon processes..."
        kill -9 $PIDS
        echo "All aon processes killed."
    else
        echo "No aon processes found."
    fi
}

# Check if a command argument is provided
if [[ -z "$1" ]]; then
    echo "Gunakan aon <hostname>. contoh: aon google.com"
    exit 1
fi

SCRIPT_NAME=$(basename "$0")

if [[ "$1" == "kill" ]]; then
    kill_aon_processes
    exit 0
fi

HOST=$1
echo "Mulai mendapatkan koneksi ke $HOST..."

while true; do
    PING_RESULT=$(ping -c 1 $HOST 2>/dev/null)
    if [[ $? -eq 0 ]]; then
        PING_TIME=$(echo "$PING_RESULT" | grep 'time=' | awk -F'time=' '{print $2}' | awk '{print $1}')
        echo "Ping ke $HOST berhasil ($PING_TIME ms)"
    else
        echo "Gagal mendapatkan koneksi ke $HOST, auto restart modem lewat /usr/bin/hilink iphunter"
        until ping -c 1 $HOST &> /dev/null; do
            /usr/bin/hilink iphunter
            /usr/bin/jam youtube.com
            sleep 80
        done
        echo "Berhasil terhubung ke $HOST. Menjalankan ping kembali"
    fi
    sleep 1
done
