#!/bin/bash
# Script by @ASHARIRHMN

#clean terminal
clear

# Check if hostnames are provided as arguments
if [ $# -eq 0 ]; then
    echo "

==============================================================
         ASHRWRT PACKAGE MANAGER BY @ASHARIRHMN   
            Last update: 17-06-2024 10.53 AM
==============================================================

Tools tersedia:
1. BugHunter
2. Freeless
3. YTDL
4. QRCODE
5. Others
6. AON

UNDUH/UPDATE
Ketik apm 1 : Untuk mengunduh/update tools Bughunter
Ketik apm 2 : Untuk mengunduh/update tools Freeless
Ketik apm 3 : Untuk mengunduh/update tools YTDL
Ketik apm 4 : Untuk mengunduh/update tools QRCODE
Ketik apm 5 : Untuk mengunduh/update tools Others (Tools dari Repo lain dengan konstumisasi ARI)
Ketik apm 6 : Untuk mengunduh/update tools AON
Ketik apm all : Untuk mengunduh/update keseluruhan tools
Ketik apm update : Untuk mengunduh/update apm package manager


MENJALANKAN PERINTAH SETELAH BERHASIL.
BugHunter: ketik 'bug' (tanda tanda petik) pada terminal untuk melihat perintah.
YTDL: ketik 'ytdl' (tanda tanda petik) pada terminal untuk melihat perintah.
QRCODE: ketik 'qr' (tanda tanda petik) pada terminal untuk melihat perintah.
AON: ketik 'aon hostname' (tanda tanda petik) pada terminal untuk menjalankan script.


"
    exit 1
fi

# Define actions for different arguments
if [ "$1" = "1" ]; then
    bash -c "$(wget -qO - 'https://raw.githubusercontent.com/letsgetwork/WRT/main/BugHunter/setup.sh')"
elif [ "$1" = "2" ]; then  # Fixed the condition to check the first argument
    bash -c "$(wget -qO - 'https://raw.githubusercontent.com/letsgetwork/WRT/main/Freeless/setup.sh')"
elif [ "$1" = "3" ]; then  # Fixed the condition to check the first argument
    bash -c "$(wget -qO - 'https://raw.githubusercontent.com/letsgetwork/WRT/main/YTDL/setup.sh')"
elif [ "$1" = "4" ]; then  # Fixed the condition to check the first argument
    bash -c "$(wget -qO - 'https://raw.githubusercontent.com/letsgetwork/WRT/main/QRCODE/setup.sh')"
elif [ "$1" = "5" ]; then  # Fixed the condition to check the first argument
    bash -c "$(wget -qO - 'https://raw.githubusercontent.com/letsgetwork/WRT/main/Others/setup.sh')"
elif [ "$1" = "6" ]; then  # Fixed the condition to check the first argument
    bash -c "$(wget -qO - 'https://raw.githubusercontent.com/letsgetwork/WRT/main/AON/setup.sh')"
elif [ "$1" = "update" ]; then  # Fixed the condition to check the first argument
    bash -c "$(wget -qO - 'https://raw.githubusercontent.com/letsgetwork/WRT/main/setup.sh')"
elif [ "$1" = "all" ]; then  # Fixed the condition to check the first argument
    bash -c "$(wget -qO - 'https://raw.githubusercontent.com/letsgetwork/WRT/main/BugHunter/setup.sh')" && 
    sleep 3 && 
    bash -c "$(wget -qO - 'https://raw.githubusercontent.com/letsgetwork/WRT/main/Freeless/setup.sh')" && 
    sleep 3 &&
    bash -c "$(wget -qO - 'https://raw.githubusercontent.com/letsgetwork/WRT/main/YTDL/setup.sh')"
    sleep 3 &&
    bash -c "$(wget -qO - 'https://raw.githubusercontent.com/letsgetwork/WRT/main/AON/setup.sh')"
    sleep 3 &&
    bash -c "$(wget -qO - 'https://raw.githubusercontent.com/letsgetwork/WRT/main/QRCODE/setup.sh')"
    sleep 2
    echo ""
    echo ""
    echo "Semua aplikasi berhasil di unduh. Enjoy 😍 "
    echo ""
    echo ""
else
    echo "Perintah tidak dikenali."
    exit 1
fi

