#!/bin/bash
#Script by @ASHARIRHMN

# Check if qrencode is installed
if ! command -v qrencode &> /dev/null; then
    echo "qrencode is not installed. Installing..."
    opkg update
    opkg install qrencode
    if [ $? -ne 0 ]; then
        echo "Error: Failed to install qrencode. Please install it manually."
        exit 1
    fi
fi

# Function to generate QR code text
generate_qr_text() {
    text=$1
    echo "QR code text for '${text}':"
    qrencode -t ANSIUTF8 "${text}"  # Output QR code as text
}

# Function to prompt user and generate QR code
qr() {
    if [ -z "$1" ]; then
        echo "

=========================================================================
  ####### QRCODE GENERATOR BY  @ASHARIRHMN #######
  Generate QRCODE via Terminal OpenWRT 😍
==========================================================================

MENJALANKAN PERINTAH
ketik 'qr' (tanda tanda petik) kemudian tulis text/url yang ingin dibuat QR code nya. Jika text digenerate lebih dari 1 kata (berupa kalimat) gunakan ''
Contoh 1 kata:  qr shopee.co.id
Contoh >1 kata/kalimat:  qr 'burung kutilang berbunyi dan menari-nari diatas pohon cemara'

"
        return 1
    fi
    clear # clean terminal before processing qrcode
    echo ""    
    generate_qr_text "$1"
    echo ""
    echo ""
}

# Call the qr function with the provided argument
qr "$@"

